### ISSUE TITLE
Could not configure bluetooth. Is bluetoothd started?

### ISSUE THREAD

**Issue by aelmahdaoui** [gh4ck3r/hid2bt#1]
I am trying to start the script but I get the error displayed in the title?
How can I correct this?

**Comment by gh4ck3r** [comment]
I think, it's about bluetooth daemon issue.
You better check the bluetooth is turned on before using this.

**Comment by aelmahdaoui** [comment]
Yes I guess even though from just the GUI of Raspbian i can pair with my computer. If i try from the terminal I get an error:
`Connection ":1.30" is not allowed to own the service "org.bluez" due to security policies in the configuration file`
I did this with sudo

**Comment by gh4ck3r** [comment]
It seems like different error message that comes from bluetooth configuration.
You may can google it.
I'm sorry for not giving you an correct answer but I don't event have raspberry for now.
